### ISSUE TITLE
混淆配置能否出个

### ISSUE THREAD

**Issue by 748297973** [yanbo469/VideoDlnaScreen#13]

**Comment by JoinLi** [comment]
#cling
-dontwarn org.eclipse.jetty.**
-dontwarn org.fourthline.cling.**
-dontwarn org.seamless.**
-keep class org.fourthline.cling.** {*;}
-keepattributes Annotation
-keep class org.seamless.statemachine.**
-keepclassmembers class * implements org.fourthline.cling.support.avtransport.impl.state.AbstractState
