### ISSUE TITLE
有实现电视端（接收端）的项目吗？

### ISSUE THREAD

**Issue by Damian007H** [yanbo469/VideoDlnaScreen#17]
看了该项目，基本可以实现投屏端的一些需求，请问该项目还在持续更新中吗？怎么可以联系到作者？
期待回复^_^

**Comment by yanbo469** [comment]
占时没有电视端接受的项目。电视端接收是底层的开发。

**Comment by Len-jidong** [comment]
> 占时没有电视端接受的项目。电视端接收是底层的开发。

**Comment by Damian007H** [comment]
> 占时没有电视端接受的项目。电视端接收是底层的开发。

感谢回复，谢谢。
